#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════
   Design Token Forge — Static Build

   Generates static JSON files from CSS tokens for GitHub Pages
   deployment. The Figma plugin polls these files for changes.

   Usage:
     node build-static.js [--out-dir ./dist]

   Output:
     dist/status.json  — lightweight hash check (plugin polls this)
     dist/tokens.json  — full Figma-compatible variable payload
   ═══════════════════════════════════════════════════════════════ */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

// ── CLI args ──────────────────────────────────────────────────

const args   = process.argv.slice(2);
const outIdx = args.indexOf('--out-dir');
const BASE_OUT_DIR = outIdx !== -1 ? path.resolve(args[outIdx + 1]) : path.resolve(__dirname, '../../dist');

const projIdx = args.indexOf('--project');
const PROJECT_ID = projIdx !== -1 ? args[projIdx + 1] : null;

// If --project is specified, output into dist/{projectId}/
const OUT_DIR = PROJECT_ID ? path.join(BASE_OUT_DIR, PROJECT_ID) : BASE_OUT_DIR;

// ── Import the server's runExport by re-using its module ──────
//    We dynamically import the server module and call runExport.
//    But since runExport isn't exported, we inline the import of
//    just the build functions. Simplest: require the whole server
//    as a build library by extracting runExport into a shared file.
//
//    For now, we use a clean approach: fork the export logic
//    by importing the server.js module path and extracting config.
//    Actually, the cleanest way is to just call the server's
//    /tokens endpoint — but that requires the server running.
//
//    Best approach: make server.js export its runExport function
//    and import it here.

// We'll import from the server module (ESM)
const serverPath = path.join(__dirname, 'server.js');

// We'll conditionally import the config→tokens generator
const generatorPath = path.join(__dirname, 'generate-from-config.js');

// ── Recursive directory copy ──────────────────────────────────
var SKIP_PATTERNS = /\.(bak|old|prev|orig)$|^_TEMPLATE\.html$|^_strip-nav\.js$|\.DS_Store$/;

function copyDirSync(src, dst) {
  fs.mkdirSync(dst, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    if (SKIP_PATTERNS.test(entry.name)) continue;
    const s = path.join(src, entry.name);
    const d = path.join(dst, entry.name);
    if (entry.isDirectory()) copyDirSync(s, d);
    else fs.copyFileSync(s, d);
  }
}

// ── Convert token overrides to CSS file content ──────────────
function tokensToCSSFile(tokens, title) {
  const ts = new Date().toISOString();
  const lines = [
    `/* ════════════════════════════════════════════════════════════════`,
    `   Design Token Forge — ${title}`,
    `   Generated by build-static.js  ${ts}`,
    `   DO NOT EDIT — regenerated automatically from project config.`,
    `   ════════════════════════════════════════════════════════════════ */`,
    '',
    ':root {'
  ];
  if (tokens.light) {
    for (const [name, val] of Object.entries(tokens.light)) {
      const src = tokens.paletteSrc?.[name] ? ` /* src: ${tokens.paletteSrc[name]} */` : '';
      lines.push(`  --${name}: ${val};${src}`);
    }
  }
  lines.push('}', '', '[data-theme="dark"] {');
  if (tokens.dark) {
    for (const [name, val] of Object.entries(tokens.dark)) {
      lines.push(`  --${name}: ${val};`);
    }
  }
  lines.push('}', '');
  return lines.join('\n');
}

async function main() {
  // Dynamically import server module to access runExport
  // First, we need to modify server.js to export runExport.
  // For the static build, we inline the necessary code instead.

  // Actually, the simplest approach: just run the server's export
  // logic by reading the same CSS files and producing the same output.
  // We achieve this by importing a shared build module.

  // For now: call the server's HTTP endpoint if running,
  // or inline the build. Let's do the inline approach since
  // this is a CI script that won't have the server running.

  console.log('');
  console.log('  Design Token Forge — Static Build');
  console.log('  ─────────────────────────────────');

  // ── Load & validate project config (if --project specified) ──
  const ROOT = path.resolve(__dirname, '../..');
  let projectConfig = null;
  if (PROJECT_ID) {
    const configPath = path.join(ROOT, 'projects', PROJECT_ID, 'config.json');
    if (!fs.existsSync(configPath)) {
      console.error(`  ✗ Project config not found: ${configPath}`);
      process.exit(1);
    }
    projectConfig = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
    console.log(`  Project: ${projectConfig.name} (${projectConfig.id})`);
  }

  // Import the build functions from server.js
  // We need to make server.js export them. Let's do that.
  let serverModule;
  try {
    serverModule = await import(serverPath);
  } catch (e) {
    console.error('  ✗ Failed to import server.js:', e.message);
    process.exit(1);
  }

  if (typeof serverModule.runExport !== 'function') {
    console.error('  ✗ server.js does not export runExport(). Please update it.');
    process.exit(1);
  }

  // ── Generate token overrides from config.json ────────────────
  //    If the project config has paletteKeys/semanticMap/surfaceMap,
  //    regenerate the token values from config (the source of truth)
  //    instead of relying solely on the CSS files.
  let exportOpts = {};
  if (projectConfig?.paletteKeys) {
    try {
      const { generateTokenOverrides } = await import(generatorPath);

      // Parse baseline primitives so non-color tokens (spacing, font) are preserved
      const TOKENS_DIR = path.join(ROOT, 'packages', 'tokens', 'src');
      const basePrimitives = serverModule.parseCSSTokens
        ? serverModule.parseCSSTokens(path.join(TOKENS_DIR, 'primitives.css'))
        : { light: {}, dark: {} };

      const overrides = generateTokenOverrides(projectConfig, basePrimitives);
      if (overrides.primitiveTokens) exportOpts.primitiveTokens = overrides.primitiveTokens;
      if (overrides.semanticTokens)  exportOpts.semanticTokens  = overrides.semanticTokens;
      if (overrides.surfaceTokens)   exportOpts.surfaceTokens   = overrides.surfaceTokens;

      const parts = [];
      if (overrides.primitiveTokens) parts.push('primitives');
      if (overrides.semanticTokens)  parts.push('semantic');
      if (overrides.surfaceTokens)   parts.push('surfaces');
      if (parts.length) console.log(`  ✓ Config overrides → ${parts.join(', ')}`);
    } catch (e) {
      console.warn(`  ⚠ Config override generation failed, falling back to CSS: ${e.message}`);
    }
  }

  // ── Load rename map (one-time migration for Figma variable renames) ──
  const renamesPath = path.join(__dirname, 'renames.json');
  if (fs.existsSync(renamesPath)) {
    try {
      const renamesData = JSON.parse(fs.readFileSync(renamesPath, 'utf-8'));
      if (renamesData.renames && Object.keys(renamesData.renames).length > 0) {
        exportOpts.renames = renamesData.renames;
        console.log(`  ✓ renames.json  → ${Object.keys(renamesData.renames).length} path renames`);
      }
    } catch (e) {
      console.warn(`  ⚠ Failed to load renames.json: ${e.message}`);
    }
  }

  const data = serverModule.runExport(exportOpts);

  // Inject project identity into the payload
  if (projectConfig) {
    data.project = { id: projectConfig.id, name: projectConfig.name };
  }

  // Ensure output dir exists
  fs.mkdirSync(OUT_DIR, { recursive: true });

  // Write tokens.json — full payload
  const tokensPath = path.join(OUT_DIR, 'tokens.json');
  fs.writeFileSync(tokensPath, JSON.stringify(data, null, 2));
  console.log(`  ✓ tokens.json  → ${data.stats.totalVariables} variables (${data.contentHash})`);

  // Read git commit SHA for deploy verification
  let buildCommit = '';
  try { buildCommit = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim(); } catch(e) {}

  // Write status.json — lightweight polling endpoint
  const status = {
    connected: true,
    hash: data.contentHash,
    lastChanged: data.exported,
    buildCommit: buildCommit,
    pendingChanges: 0,
    totalVariables: data.stats.totalVariables,
    totalCollections: data.stats.totalCollections,
    lastSyncedHash: '',
    ...(projectConfig && { project: { id: projectConfig.id, name: projectConfig.name } })
  };
  const statusPath = path.join(OUT_DIR, 'status.json');
  fs.writeFileSync(statusPath, JSON.stringify(status, null, 2));
  console.log(`  ✓ status.json  → hash ${data.contentHash}`);

  // Root index.html — redirect to demo/ hub (all navigation lives there)
  const indexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="refresh" content="0;url=demo/index.html">
<title>Design Token Forge</title>
</head>
<body>
<p>Redirecting to <a href="demo/index.html">Design Token Forge</a>…</p>
</body>
</html>`;
  fs.writeFileSync(path.join(OUT_DIR, 'index.html'), indexHtml);
  console.log('  ✓ index.html   → landing page');

  // ── Copy demo pages + dependencies ──────────────────────────
  const demoSrc = path.join(ROOT, 'demo');
  const demoDst = path.join(OUT_DIR, 'demo');

  if (fs.existsSync(demoSrc)) {
    copyDirSync(demoSrc, demoDst);
    console.log('  ✓ demo/        → component explorer');

    // Copy packages/ (tokens + components CSS) so ../packages/ refs work
    const pkgSrc = path.join(ROOT, 'packages');
    const pkgDst = path.join(OUT_DIR, 'packages');
    // Only copy what demos need: tokens/src and components/src
    const tokensSrc = path.join(pkgSrc, 'tokens', 'src');
    const tokensDst = path.join(pkgDst, 'tokens', 'src');
    if (fs.existsSync(tokensSrc)) {
      copyDirSync(tokensSrc, tokensDst);
      console.log('  ✓ packages/tokens/src/');
    }

    // Overwrite surface CSS with per-project values from config overrides
    if (exportOpts.surfaceTokens) {
      const surfPath = path.join(tokensDst, 'surfaces.css');
      const surfCSS = tokensToCSSFile(exportOpts.surfaceTokens, 'T2 Surface Context Tokens');
      fs.writeFileSync(surfPath, surfCSS);
      console.log('  ✓ surfaces.css  → per-project overrides from config');
    }
    if (exportOpts.primitiveTokens) {
      const primPath = path.join(tokensDst, 'primitives.css');
      const primCSS = tokensToCSSFile(exportOpts.primitiveTokens, 'T0 Primitive Colors');
      fs.writeFileSync(primPath, primCSS);
    }
    if (exportOpts.semanticTokens) {
      const semPath = path.join(tokensDst, 'semantic.css');
      const semCSS = tokensToCSSFile(exportOpts.semanticTokens, 'T1 Semantic Tokens');
      fs.writeFileSync(semPath, semCSS);
    }
    const compSrc = path.join(pkgSrc, 'components', 'src');
    const compDst = path.join(pkgDst, 'components', 'src');
    if (fs.existsSync(compSrc)) {
      copyDirSync(compSrc, compDst);
      console.log('  ✓ packages/components/src/');
    }
  }

  // ── Backward compatibility: mirror full output to dist root ──
  if (PROJECT_ID) {
    // Copy tokens + status to root
    fs.copyFileSync(path.join(OUT_DIR, 'tokens.json'), path.join(BASE_OUT_DIR, 'tokens.json'));
    fs.copyFileSync(path.join(OUT_DIR, 'status.json'), path.join(BASE_OUT_DIR, 'status.json'));
    fs.copyFileSync(path.join(OUT_DIR, 'index.html'), path.join(BASE_OUT_DIR, 'index.html'));
    // Mirror demo + packages so existing GitHub Pages URLs keep working
    const rootDemo = path.join(BASE_OUT_DIR, 'demo');
    const rootPkg  = path.join(BASE_OUT_DIR, 'packages');
    if (fs.existsSync(path.join(OUT_DIR, 'demo')))     copyDirSync(path.join(OUT_DIR, 'demo'), rootDemo);
    if (fs.existsSync(path.join(OUT_DIR, 'packages'))) copyDirSync(path.join(OUT_DIR, 'packages'), rootPkg);
    console.log(`  ✓ Backward compat → mirrored to dist/ root`);
  }

  // ── Deploy project config.json so demo pages can load it ────
  if (PROJECT_ID && projectConfig) {
    const cfgDst = path.join(OUT_DIR, 'config.json');
    fs.writeFileSync(cfgDst, JSON.stringify(projectConfig, null, 2));
    console.log('  ✓ config.json  → project configuration');
    // Also mirror to dist root for backward compat
    fs.copyFileSync(cfgDst, path.join(BASE_OUT_DIR, 'config.json'));
  }

  // ── Write per-project CSS to projects/{id}/ for local dev switching ──
  if (PROJECT_ID) {
    const projCSSDir = path.join(ROOT, 'projects', PROJECT_ID);
    fs.mkdirSync(projCSSDir, { recursive: true });
    if (exportOpts.primitiveTokens) {
      fs.writeFileSync(path.join(projCSSDir, 'primitives.css'),
        tokensToCSSFile(exportOpts.primitiveTokens, 'T0 Primitive Colors'));
    }
    if (exportOpts.semanticTokens) {
      fs.writeFileSync(path.join(projCSSDir, 'semantic.css'),
        tokensToCSSFile(exportOpts.semanticTokens, 'T1 Semantic Tokens'));
    }
    if (exportOpts.surfaceTokens) {
      fs.writeFileSync(path.join(projCSSDir, 'surfaces.css'),
        tokensToCSSFile(exportOpts.surfaceTokens, 'T2 Surface Context Tokens'));
    }
    if (exportOpts.primitiveTokens || exportOpts.semanticTokens || exportOpts.surfaceTokens) {
      console.log(`  ✓ projects/${PROJECT_ID}/*.css → local dev switching`);
    }
  }

  // ── Generate projects.json manifest ─────────────────────────
  const projectsDir = path.join(ROOT, 'projects');
  if (fs.existsSync(projectsDir)) {
    const projectList = [];
    for (const entry of fs.readdirSync(projectsDir, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const cfgPath = path.join(projectsDir, entry.name, 'config.json');
      if (!fs.existsSync(cfgPath)) continue;
      const cfg = JSON.parse(fs.readFileSync(cfgPath, 'utf-8'));
      projectList.push({ id: cfg.id, name: cfg.name, description: cfg.description || '' });
    }
    const manifestPath = path.join(BASE_OUT_DIR, 'projects.json');
    fs.writeFileSync(manifestPath, JSON.stringify(projectList, null, 2));
    console.log(`  ✓ projects.json → ${projectList.length} project(s)`);
  }

  console.log('');
  console.log(`  Output: ${OUT_DIR}`);
  console.log(`  Deploy this folder to GitHub Pages.`);
  console.log('');
}

main().catch(e => {
  console.error('Build failed:', e);
  process.exit(1);
});
